// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NhWj15r6TeMau2b_SiB8hRIUi-wmLG8',
    appId: '1:876754816088:web:59e8b59c0eceb0c6de4e2d',
    messagingSenderId: '876754816088',
    projectId: 'fir-options-beafd',
    authDomain: 'fir-options-beafd.firebaseapp.com',
    storageBucket: 'fir-options-beafd.firebasestorage.app',
    measurementId: 'G-G8ST8WFC15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqsNJUETe2hTO5_k51w01WnDItGiEJOY',
    appId: '1:876754816088:android:7924b3b680f2d71ede4e2d',
    messagingSenderId: '876754816088',
    projectId: 'fir-options-beafd',
    storageBucket: 'fir-options-beafd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfs9AxLU17G4YQ1ogAgNW_Hdj9Xlg-FCw',
    appId: '1:876754816088:ios:7eb5e6cb1d55d119de4e2d',
    messagingSenderId: '876754816088',
    projectId: 'fir-options-beafd',
    storageBucket: 'fir-options-beafd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfs9AxLU17G4YQ1ogAgNW_Hdj9Xlg-FCw',
    appId: '1:876754816088:ios:7eb5e6cb1d55d119de4e2d',
    messagingSenderId: '876754816088',
    projectId: 'fir-options-beafd',
    storageBucket: 'fir-options-beafd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2NhWj15r6TeMau2b_SiB8hRIUi-wmLG8',
    appId: '1:876754816088:web:9f0fa63e894bceabde4e2d',
    messagingSenderId: '876754816088',
    projectId: 'fir-options-beafd',
    authDomain: 'fir-options-beafd.firebaseapp.com',
    storageBucket: 'fir-options-beafd.firebasestorage.app',
    measurementId: 'G-03VFN3EBQJ',
  );
}
