// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2xdtiG51SaWdUEEyv84-2bvVwZ0NjdqQ',
    appId: '1:440599813246:web:eda91139709bb2cefb0c2f',
    messagingSenderId: '440599813246',
    projectId: 'fir-project-e80c0',
    authDomain: 'fir-project-e80c0.firebaseapp.com',
    storageBucket: 'fir-project-e80c0.firebasestorage.app',
    measurementId: 'G-S9XGWCK7V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkyq5q9uLo-yUEpqpiBBp-VTpypt29ds',
    appId: '1:440599813246:android:c6efa80fd140b562fb0c2f',
    messagingSenderId: '440599813246',
    projectId: 'fir-project-e80c0',
    storageBucket: 'fir-project-e80c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYlGfnBLcUOd3wlWmYbiFMce9DeRztEAI',
    appId: '1:440599813246:ios:45b3b2feecc1616cfb0c2f',
    messagingSenderId: '440599813246',
    projectId: 'fir-project-e80c0',
    storageBucket: 'fir-project-e80c0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYlGfnBLcUOd3wlWmYbiFMce9DeRztEAI',
    appId: '1:440599813246:ios:45b3b2feecc1616cfb0c2f',
    messagingSenderId: '440599813246',
    projectId: 'fir-project-e80c0',
    storageBucket: 'fir-project-e80c0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2xdtiG51SaWdUEEyv84-2bvVwZ0NjdqQ',
    appId: '1:440599813246:web:8ef6b836a5a73f08fb0c2f',
    messagingSenderId: '440599813246',
    projectId: 'fir-project-e80c0',
    authDomain: 'fir-project-e80c0.firebaseapp.com',
    storageBucket: 'fir-project-e80c0.firebasestorage.app',
    measurementId: 'G-2EX0BSFM06',
  );
}
